name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: dessant/lock-threads@v5
        with: 
          issue-inactive-days: '14'
          process-only: 'issues'
